### ISSUE TITLE
plot_cross_section color map error

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVMC#30]
The following command errors out on color map issue.

-bash-4.2$ ./plot_cross_section.py -b 34.0,-118.0 -u 35.0,-117.0 -h 100 -v 10 -d vs -c cvms -a d -s 0 -e 500
Using parameters:

lat1 = 34.0
data_type = vs
lat2 = 35.0
cvm_selected = cvms
ending_depth = 500
horizontal_spacing = 100
color = d
lon1 = -118.0
vertical_spacing = 10
lon2 = -117.0
starting_depth = 0

Retrieving data. Please wait...
Traceback (most recent call last):
  File "./plot_cross_section.py", line 204, in <module>
    d.plot(data_type)
  File "/home/scec-00/maechlin/t1/utilities/pycvm/pycvm/cross_section.py", line 201, in plot
    img = plt.imshow(datapoints, cmap=colormap, norm=norm)
UnboundLocalError: local variable 'colormap' referenced before assignment

**Comment by pjmaechling** [comment]
This was resolved with a modification to pycvm/cross_section.py which initialized the colormap before use.
