### ISSUE TITLE
plot_cross_section.py errors 

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVMC#35]
This call of plot_cross_section error. Looks like it should. Figure out why it fails.

-bash-4.2$ ./plot_cross_section.py -b 34.0,-118.75 -u 34.0,-117.5 -s 0 -e 1000 -h 500 -v 5 -d vs -a s -c cvm5
Using parameters:

starting_depth = 0
data_type = vs
ending_depth = 1000
vertical_spacing = 5
lat2 = 34.0
horizontal_spacing = 500
color = s
lon1 = -118.75
lat1 = 34.0
cvm_selected = cvm5
lon2 = -117.5

Retrieving data. Please wait...
Traceback (most recent call last):
  File "./plot_cross_section.py", line 204, in <module>
    d.plot(data_type)
  File "/home/scec-00/maechlin/t1/utilities/pycvm/pycvm/cross_section.py", line 128, in plot
    self.getplotvals()
  File "/home/scec-00/maechlin/t1/utilities/pycvm/pycvm/cross_section.py", line 90, in getplotvals
    data = u.query(point_list, self.cvm)
  File "/home/scec-00/maechlin/t1/utilities/pycvm/pycvm/common.py", line 342, in query
    properties.append(MaterialProperties.fromUCVMOutput(line))
  File "/home/scec-00/maechlin/t1/utilities/pycvm/pycvm/common.py", line 246, in fromUCVMOutput
    return cls(new_line[14], new_line[15], new_line[16])
IndexError: list index out of range

**Comment by meihuisu** [comment]
with newer version, the problem is pinpointed:

ERROR:  Model cvm5 is not a valid model. It was not enabled when UCVM was compiled or the config key cvm5_modelpath is not defined.
