### ISSUE TITLE
horizontal slice errors on rho or poisson data types

### ISSUE THREAD

**Issue by pjmaechling** [SCECcode/UCVMC#37]
-bash-4.2$ ./plot_horizontal_slice.py -b 33.5,-118.75 -u 34.5,-117.5 -s 0.1 -e 500 -d rho -a s -c cvmh
Using parameters:

lat1 = 33.5
data_type = rho
lat2 = 34.5
color = s
spacing = 0.1
cvm_selected = cvmh
depth = 500
lon1 = -118.75
lon2 = -117.5

Retrieving data. Please wait...
Traceback (most recent call last):
  File "./plot_horizontal_slice.py", line 185, in <module>
    h.plot(data_type, color_scale=color)
  File "/home/scec-00/maechlin/t1/utilities/pycvm/pycvm/horizontal_slice.py", line 179, in plot
    datapoints[i][j] = self.materialproperties[i][j].getProperty(property) / 1000.0
  File "/home/scec-00/maechlin/t1/utilities/pycvm/pycvm/common.py", line 265, in getProperty
    raise ValueError("Parameter property must be a valid material property unit.")
ValueError: Parameter property must be a valid material property unit.
-bash-4.2$ ./plot_horizontal_slice.py -b 33.5,-118.75 -u 34.5,-117.5 -s 0.1 -e 500 -d poission -a s -c cvmh
Using parameters:

lat1 = 33.5
data_type = poission
lat2 = 34.5
color = s
spacing = 0.1
cvm_selected = cvmh
depth = 500
lon1 = -118.75
lon2 = -117.5

Retrieving data. Please wait...
Traceback (most recent call last):
  File "./plot_horizontal_slice.py", line 185, in <module>
    h.plot(data_type, color_scale=color)
  File "/home/scec-00/maechlin/t1/utilities/pycvm/pycvm/horizontal_slice.py", line 179, in plot
    datapoints[i][j] = self.materialproperties[i][j].getProperty(property) / 1000.0
  File "/home/scec-00/maechlin/t1/utilities/pycvm/pycvm/common.py", line 265, in getProperty
    raise ValueError("Parameter property must be a valid material property unit.")
ValueError: Parameter property must be a valid material property unit.

**Comment by meihuisu** [comment]
option for data type:  vs, vp, density and poisson

for poisson data_type, it is better to use color scale of either 'dd' or 'sd'
